# Problem Link: https://codeforces.com/contest/1138/problem/A

SushiForTwo  ← {2×⌈´⌊´˘2↕≠¨𝕩⊔˜0∾+`≠´˘2↕𝕩}     # Explicit
SushiForTwo2 ← 2×·⌈´·⌊´˘2↕·≠¨(0∾·+`·≠´˘2↕⊢)⊸⊔ # Tacit :(

# Tests
•Show SushiForTwo  ⟨2,2,2,1,1,2,2⟩     # 4
•Show SushiForTwo  ⟨1,2,1,2,1,2⟩       # 2
•Show SushiForTwo  ⟨2,2,1,1,1,2,2,2,2⟩ # 6
•Show SushiForTwo2 ⟨2,2,2,1,1,2,2⟩     # 4
•Show SushiForTwo2 ⟨1,2,1,2,1,2⟩       # 2
•Show SushiForTwo2 ⟨2,2,1,1,1,2,2,2,2⟩ # 6
